version: "3.8"

services:
  web:
    container_name: web
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - VUE_APP_GRAPHQL_ENDPOINT=http://localhost:8000/graphql
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - mono-node_modules:/app/node_modules

  api:
    container_name: api
    depends_on:
      - postgresql
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --fail http://localhost:8000/healthz || exit 1
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 30s
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    environment:
      - APP_PORT=8000
      - DATABASE_URL=postgres://postgres:pw0628@postgresql/test?schema=public # postgres://username:password@host:port/database?schema=schema
      - SHOULD_ENABLE_PLAYGROUND=true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - mono-node_modules:/app/node_modules

  postgresql:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: pw0628
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5434:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: null
  mono-node_modules: null
